MaGaBoo/final-project-web

package-lock.json, package.json, src/index.js
No he hecho nada jeje solo es para probar que no la lio creando nuevas ramas y haciendo pull a la rama principal
=> New branch test

src/views/Plants/PlantDetail/PlantDetail.jsx
Se puede ver el detalle de una planta desde el front!! No muestra el booleano del pet friendly por error mío al crear la planta, pero lo demás está correcto
=> feat: plant detail view shows data

package-lock.json, src/views/Plants/NewPlant/NewPlant.jsx, src/views/Plants/PlantDetail/PlantDetail.jsx
=> feat: new plant from web

package-lock.json, src/App.js, src/components/Navbar/Navbar.jsx, src/contexts/AuthContext.js, src/services/AuthService.js, src/services/BaseService.js, src/services/UsersService.js, src/store/AccessTokenStore.js, src/views/Login/Login.jsx, src/views/Profile/Profile.js, src/views/Register/Register.jsx
@MaGaBoo ya funciona el login. En general íbamos por buen camino, pero he visto que no teníamos bien el archivo BaseService (front) y que en routes (back) teníamos dos peticiones a login.
Echa un ojo cuando puedas. Graciaaaa!
=> Test login user

src/App.js, src/components/Footer/Footer.js, src/components/Footer/Footer.scss, src/views/Login/Login.jsx
Created footer component, no styles or content added yet
=> created footer component

src/App.js, src/views/Categories/CactusAndSucculents/CactusAndSucculents.js, src/views/Categories/Evergreen/Evergreen.js, src/views/Categories/Orchids/Orchids.js, src/views/Home/Home.jsx
Created views from home to different categories:
- Evergreen 🌱
- Orchids 🌺
- Cactus and Succulents 🌵
=> created categories views

src/components/PlantsList/PlantList.js, src/data/plants.json
- Added links to plants listed at PlantsList component
- Added "id" field to plants.json
=> added links to plantsList

src/contexts/CartContext.js
He cambio el estado por defecto del carrito para que coja los productos del carrito del local storage. Sino, perdemos esos productos cuando actualizamos la página.
=> Cart context from local storage

src/components/Cart/Cart.jsx, src/contexts/CartContext.js, src/views/Profile/Profile.js
Ya se puede eliminar los productos del carrito 😎
=> feat: delete cart products

src/services/OrdersService.js, src/views/Checkout/Checkout.js, src/views/Orders/Orders.js
- Create orderService
- Create order view to render confirmed orders
- Main problem is clarify what should receive. At this moment newOrder it equal to 💩💩💩
=> create order view

src/App.js, src/components/Navbar/Navbar.jsx, src/services/OrdersService.js, src/views/Checkout/Checkout.js, src/views/Orders/OrderDetail/OrderDetail.jsx, src/views/Orders/Orders.js
He cambiado un poco la vista de orders porque me parece que en esa vista deberían estar todos los pedidos de un usuario y que se pueda hacer click que te lleve a ese pedido en concreto con todos los detalles del mismo. ¿Cómo lo ves?
No está completo porque ahora mismo se trae todas las roders de la bbdd. Habría que especificar que solo se traiga los del user logeado. ¿Cómo lo ves?
=> feat: change order view and created order detail

src/contexts/CartContext.js, src/views/Checkout/Checkout.js, src/views/Orders/Orders.js, src/views/Plants/EditPlant/EditPlant.jsx
Además de que el usuario logueado solo pueda ver sus orders, también he hecho que en local storage desaparezca los productos del carrito después de hacer una compra, peeero en el front no se actualiza/borra el carrito hasta que se recarga la página. Hay que ver cómo solucionarlo : )
=> feat: logged user only can see his/her orders

src/contexts/CartContext.js, src/services/PlantService.js, src/views/Categories/Evergreen/Evergreen.js
- filterPlants added to PlantService
- evergreen view render filtered <PlantList /> element
=> evergreen view render evergreen category plants

public/index.html, src/views/Checkout/Checkout.js
- added button to delete products in checkout view
- if you buy same plant several times, you can´t delete just one at this moment. need to add counter to + -
=> delete button added to checkout

src/views/Orders/OrderDetail/OrderDetail.jsx
Order detail already show all products'name, their prices, order's total and the payment's date.
=> feat: order detail shows all order info

src/App.js, src/components/Navbar/Navbar.jsx, src/views/Checkout/Checkout.js, src/views/Profile/Profile.js
Profile view show orders and plants. Maybe we don't need the "orders" component anymore. In the meantime, i commented that in navbar and app.js
=> feat: profile view show his/her orders and plants

src/App.js, src/views/Plants/PlantDetail/PlantDetail.jsx
Maríaaa! Esto mejor te lo digo en español XD
He seguido tu idea para que el usuario no pueda comprar un producto que ha añadido al carrito, pero no está completo al 100%. Si el usuario le da "add to cart" el botón desaparece, peeero si sale de la vista del producto y vuelve a entrar el muy cabrón vuelve a aparecer :/
No hace falta que sigas mi código. Puedes seguir intentándolo por tu cuenta que seguro que lo solucionas del todo :)
=> feat: can see product detail even if the user is not log in

public/index.html, src/assets/stylesheets/general_mixins.scss, src/assets/stylesheets/variables.scss, src/components/Cart/Cart.scss, src/views/Home/Home.scss, src/views/Register/Register.jsx, src/views/Register/Register.scss
Los estilos generales están en src/assets/stylesheets. Son dos archivos .scss en donde hay variables para reutilizar a lo largo de la web y otro con estilos generales y mixins.
Esto último lo vimos en la clase de Marcos y yo lo suelo usar para crear estilos para los botones y para usar display flex. A modo de ejemplo he dado estilos al botón de register, pero avísame si tienes cualquier duda : )
=> feat: add generales styles

package-lock.json, package.json, src/views/Checkout/Checkout.js, src/views/Checkout/Checkout.scss, src/views/Plants/PlantDetail/PlantDetail.jsx, src/views/Plants/PlantDetail/PlantDetail.scss
start checkout view design: understand and apply variables, mixins etc
** necesito preguntarte algunas cosas...
=> first approach to scss doing checkout view

src/App.js, src/App.scss, src/assets/stylesheets/general_mixins.scss, src/views/Checkout/Checkout.js, src/views/Home/Home.jsx, src/views/Home/Home.scss, src/views/Profile/Profile.js, src/views/Profile/Profile.scss
@MaGaBoo he modificado el archivo del "Checkout" porque "button" estaba fuera del formulario de pago y no se podía hacer ninguna compra.
Además, adjunto cómo se ve la página de "Profile"
.
=> feat: profile page design. NOT responsive yet

public/index.html, src/components/Navbar/Navbar.jsx, src/components/Navbar/Navbar.scss, src/views/Categories/CactusAndSucculents/CactusAndSucculents.js, src/views/Categories/Orchids/Orchids.js, src/views/Plants/PlantDetail/PlantDetail.scss
- cart dropdown is working without styles
- also updated categories names
=> cart dropdown without styles
